server:
  port: 0
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/main-db
    driver-class-name: "org.postgresql.Driver"
    username: "postgres"
    password: "824322"

stats-server:
  service-id: stats-server