server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/practicum_db
    username: your_db_user
    password: your_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false
      encoding: UTF-8