server:
  port: 0

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-categories-route
          uri: lb://main-service
          predicates:
            - Path=/categories/**,/categories
          filters:
            - PrefixPath=/admin

        - id: admin-users-route
          uri: lb://main-service
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/admin

        - id: admin-compilations-route
          uri: lb://main-service
          predicates:
            - Path=/compilations/**
          filters:
            - PrefixPath=/admin

        - id: admin-events-route
          uri: lb://main-service
          predicates:
            - Path=/events/**
          filters:
            - PrefixPath=/admin

        - id: admin-moderation-route
          uri: lb://main-service
          predicates:
            - Path=/events/moderation,/events/{eventId}/moderate
          filters:
            - PrefixPath=/admin

        - id: public-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**,/categories

        - id: public-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**,/compilations

        - id: public-events
          uri: lb://main-service
          predicates:
            - Path=/events/**,/events

        - id: user-events-route
          uri: lb://main-service
          predicates:
            - Path=/{userId}/events/**
          filters:
            - PrefixPath=/users

        - id: user-requests-route
          uri: lb://main-service
          predicates:
            - Path=/{userId}/requests/**,/{userId}/requests
          filters:
            - PrefixPath=/users

        - id: user-moderation-comments-route
          uri: lb://main-service
          predicates:
            - Path=/{userId}/events/{eventId}/moderation-comments
          filters:
            - PrefixPath=/users

        - id: stats-service-post
          uri: lb://stats-server
          predicates:
            - Path=/hit
            - Method=POST

        - id: stats-service-get
          uri: lb://stats-server
          predicates:
            - Path=/stats
            - Method=GET