server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stats-db
    username: postgres
    password: 824322
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info