server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/main-db
    username: "postgres"
    password: "824322"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  sql:
    init.mode: always

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}